### ISSUE TITLE
Valido-React: DateTime picker onBlur not working correctly. Look into other alternatives.

### ISSUE THREAD

**Issue by giovanni0918** [giovanni0918/valido#2]
The react demo is currently using [YouCanBookMe/react-datetime](https://github.com/YouCanBookMe/react-datetime) as its DateTime picker.

Upon testing, I noticed the on Blur event was not firing on multiple occasions when I tabbed or clicked out.

Open to suggestions.

**Comment by jdiaz** [comment]
What test did you do here? `onBlur` seems to fire 100% of the time every time I click away from the DatePicker.
Code:
`App.js`
```javascript
 <Datetime
    timeFormat={false}
    inputProps={{
      className: "form-control",
      id: "DateofBirth",
      name: "DateofBirth",
    }}
    onBlur={() => {
      console.log('blur! callback triggered');
    }}
 />
```
Before selecting a date:
![image](https://user-images.githubusercontent.com/5333759/39931807-7dd1b67c-550c-11e8-896f-21164b82b233.png)
After selecting a date:
![image](https://user-images.githubusercontent.com/5333759/39931843-92b5e342-550c-11e8-8694-f4d580910a52.png)
